### PR TITLE
Update dependencies to latest upstream (notably winit -> 0.30, wgpu -> 0.20, accesskit -> 0.16)

### PR DESCRIPTION
**Pull request by maaku**
As noted in [a vger-rs pull request](https://github.com/audulus/vger-rs/pull/20), I'm currently investigating use of rui for a cross-platform application supporting desktop + mobile + web, and built on winit and wgpu. This brings rui's dependencies up to the latest released version, which are the same I'm using in my app.

Note the diff is quite large! The winit API in particular changed significantly between 0.28 and 0.30. I've tried to keep the same business logic, and the API is unchanged even though some upstream improvements might want to be reflected in rui's API.

Of particular note, the way winit handles keyboard input has been completely rewritten and supports significantly more than is exposed by rui. I have updated the `rui()` application runner to use these new APIs, but with the same old exposed input interface. One area in which this might actually be an issue is with multi-code-point character input. Rui's API sends a single character per keystroke, whereas winit sends a string. This is because some characters in some input schemes may not reduce down to a single Unicode glyph, instead using combining character codes. The new interface (which uses winit to do key -> character transformation rather than hard coding it as rui did before) will just send on only the first Unicode code point.

Also: the vger dependency is hard-coded to the latest trunk commit as of the time of this writing, rather than a proper crates.io release. Vger should probably have a 0.3 release (since updating wgpu is breaking for downstream apps), and then rui semver-pegs to that.

### CODE REVIEW

**Comment by wtholliday** [comment]
I'll release a new version of vger to crates.io :)

**Comment by wtholliday** [comment]
Oh whoops I did 0.2.9 for vger thinking that its own API didn't change. Guess I'll do a 0.3 now

**Comment by wtholliday** [comment]
Ok 0.3.0 is up (I yanked 0.2.9). Go ahead and update your PR :)

**Comment by maaku** [comment]
Updated :)

**Comment by wtholliday** [comment]
Hey @maaku, if you run the `gallery` example and try the text editor widget, typing a letter will enter two letters (on macOS at least).

**Comment by maaku** [comment]
I didn't realize in the refactor that the keyboard events are only passed on when the event is a key press. Fixed. I can rebase when it's ready for merge.

**Comment by wtholliday** [comment]
Seems good now! After your rebase is it ready to merge?

**Comment by maaku** [comment]
Yeah, ready for merge. I just force-pushed a rebased fix.

**Comment by wtholliday** [comment]
Thanks!!

**Pull request merged**
