### PR TITLE
Versions of hover, drag, tap which pass the mouse position and button.

### PR DESCRIPTION
**Pull request by ruza-net**
Added modifiers `hover_p`, `drag_p`, `tap_p` which pass the mouse position and button, where applicable.

### CODE REVIEW

**Comment by wtholliday** [comment]
Hey thanks! Could we modify the existing structs to take a closure with position instead of having new structs with mostly duplicate code?

**Comment by wtholliday** [comment]
I tried this:
```rust
    /// Calls a function in response to a tap.
    fn tap<A: 'static, F: Fn(&mut Context) -> A + 'static, F2: Fn(&mut Context, LocalPoint, Option<MouseButton>) -> A + 'static>(self, f: F) -> Tap<Self, F2> {
        Tap::new(self, move |cx, _, _ | f(cx))
    }

    fn tap_p<A: 'static, F: Fn(&mut Context, LocalPoint, Option<MouseButton>) -> A + 'static>(self, f: F) -> Tap<Self, F> {
        Tap::new(self, f)
    }
```

But the closure doesn't match the type: 

image

**Comment by ruza-net** [comment]
It's an interesting idea, maybe I can get it to work somehow...

**Comment by wtholliday** [comment]
@ruza-net I figured it out after merging this one :)

https://github.com/audulus/rui/pull/58

and subsequent commits

**Pull request merged**
